### ISSUE TITLE
feature request: the version of a dependency package should be exported too

### ISSUE THREAD

**Issue by ClausKlein** [TheLartians/PackageProject.cmake#12]
How can I require the version of my dependencies?

```cmake
packageProject(
    NAME ${PROJECT_NAME}
    VERSION ${PROJECT_VERSION}
    NAMESPACE ${PROJECT_NAME}
    BINARY_DIR ${PROJECT_BINARY_DIR}
    INCLUDE_DIR ${PROJECT_SOURCE_DIR}/include
    INCLUDE_DESTINATION include/${PROJECT_NAME}
    VERSION_HEADER "${VERSION_HEADER_LOCATION}"
    DEPENDENCIES "" # optional list of dependencies, FIXME: but without requiered version?
)
```

**Comment by TheLartians** [comment]
Good point! As all arguments are forwarded to `find_dependency`, you should be able to specify the version and additional options in the dependencies list. For example:

```cmake
packageProject(
  NAME ${PROJECT_NAME}
  VERSION ${PROJECT_VERSION}
  NAMESPACE ${PROJECT_NAME}
  BINARY_DIR ${PROJECT_BINARY_DIR}
  INCLUDE_DIR ${PROJECT_SOURCE_DIR}/include
  INCLUDE_DESTINATION include/${PROJECT_NAME}-${PROJECT_VERSION}
  VERSION_HEADER "${VERSION_HEADER_LOCATION}"
  DEPENDENCIES "fmt 7.1.3;cxxopts 2.2.0"
)
```

We should update the documentation accordingly.

FYI: the `BINARY_DIR` parameter is indeed used to indicate where to store the version include header and CMake package  config file before installation.

**Comment by ClausKlein** [comment]
>   DEPENDENCIES "fmt 7.1.3;cxxopts 2.2.0"
> 
> We should update the documentation accordingly.
> 
> FYI: the `BINARY_DIR` parameter is indeed used to indicate where to store the version include header and CMake package config file before installation.

Oh, good idea! I didn't see this solution.

but the `BINARY_DIR` parameter is intended for this, but not used in the implementation of the function!

**Comment by ClausKlein** [comment]
Oops:
```Claus-iMac:unused clausklein$ cmake -B build -S .
CMake Error at /usr/local/Cellar/cmake/3.19.4/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Find7.1.3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "7.1.3", but
  CMake did not find one.

  Could not find a package configuration file provided by "7.1.3" with any of
  the following names:

    7.1.3Config.cmake
    7.1.3-config.cmake

  Add the installation prefix of "7.1.3" to CMAKE_PREFIX_PATH or set
  "7.1.3_DIR" to a directory containing one of the above files.  If "7.1.3"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/Greeter-1.0/GreeterConfig.cmake:30 (find_dependency)
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/clausklein/cmake/unused/build/CMakeFiles/CMakeOutput.log".
See also "/Users/clausklein/cmake/unused/build/CMakeFiles/CMakeError.log".
Claus-iMac:unused clausklein$ 
```

**Comment by TheLartians** [comment]
Seems CMake split the string at the space instead of the semicolon. Is there a semicolon in the dependencies string?
If you have only a single dependency, could you try adding one in the end: `"fmt 7.1.3;"`?

**Comment by TheLartians** [comment]
Or did you forget the quotes? It would be super helpful if you could post the CMake code, otherwise I'm just guessing.

**Comment by ClausKlein** [comment]
I used  this: 

`DEPENDENCIES "FMT ${FMT_VERSION}"`

**Comment by ClausKlein** [comment]
this may help:
```cmake
# Quote all the semicolons in cmake list variable
string(REPLACE ";" "\\;" QUOTED_CMAKE_PREFIX_PATH
       "${CMAKE_PREFIX_PATH}"
)
```

**Comment by TheLartians** [comment]
As a workaround adding a second dummy dependency should also convince CMake to split at semicolons: `DEPENDENCIES "FMT ${FMT_VERSION};FMT ${FMT_VERSION}"`. I'll see if there is a way to convince CMake to split at semicolons only.

**Comment by ClausKlein** [comment]
NO, it is not possible in this way!
```shell
CMake Error at /usr/local/Cellar/cmake/3.19.4/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindFMT 7.1.3.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by "FMT
  7.1.3", but CMake did not find one.
```
see [CMakeFindDependencyMacro](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html)

better to use `find_package()` with the right parameters direct!

**Comment by TheLartians** [comment]
Turns out CMake's string/array handling is much more volatile than I thought. The new version uses regexes to split the dependency strings and should hopefully work. See the [example](https://github.com/TheLartians/PackageProject.cmake/blob/v1.4.1/test/transitive_dependency/CMakeLists.txt) in the tests directory.
