### ISSUE TITLE
FeatureRequest: make it optional to install the package to version less subdirectories

### ISSUE THREAD

**Issue by ClausKlein** [TheLartians/PackageProject.cmake#13]
IMHO it would be nice to be able to install a static library in this way:

```shell
Claus-iMac:example clausklein$ ninja -C build install
ninja: Entering directory `build'
[0/1] Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/Greeter/libGreeter.a
-- Installing: /usr/local/lib/cmake/Greeter/GreeterTargets.cmake
-- Installing: /usr/local/lib/cmake/Greeter/GreeterTargets-noconfig.cmake
-- Installing: /usr/local/lib/cmake/Greeter/GreeterConfigVersion.cmake
-- Installing: /usr/local/lib/cmake/Greeter/GreeterConfig.cmake
-- Up-to-date: /usr/local/include/Greeter
-- Up-to-date: /usr/local/include/Greeter/greeter
-- Up-to-date: /usr/local/include/Greeter/greeter/greeter.h
Claus-iMac:example clausklein$ 
```

with `set(PROJECT_COMPATIBILITY AnyNewerVersion)`
a newer version would be found and used, or not?

**Comment by TheLartians** [comment]
I disagree, as it's not unusual for projects to contain breaking changes in updates. Otherwise you would either need to require a stable API and ABI between all releases (maintenance nightmare) or live with knowing that all dependents of your project could break or become unstable at any time after an update.

**Comment by ClausKlein** [comment]
As an option it would be nice, but not easy to configure.

Most project do not use version postfix. On my mac, if found this:

```shell
Claus-iMac:example clausklein$ tree -d -L 2 /usr/local/lib/cmake/
/usr/local/lib/cmake/
├── Boost-1.75.0 -> ../../Cellar/boost/1.75.0_1/lib/cmake/Boost-1.75.0
├── Example
├── Greeter
├── Greeter-1.0
├── Poco
├── Snappy
├── absl -> ../../Cellar/abseil/20200923.3/lib/cmake/absl
├── asio
├── boost_atomic-1.75.0 -> ../../Cellar/boost/1.75.0_1/lib/cmake/boost_atomic-1.75.0
├── boost_chrono-1.75.0 -> ../../Cellar/boost/1.75.0_1/lib/cmake/boost_chrono-1.75.0

#  ... 

├── boost_wave-1.75.0 -> ../../Cellar/boost/1.75.0_1/lib/cmake/boost_wave-1.75.0
├── boost_wserialization-1.75.0 -> ../../Cellar/boost/1.75.0_1/lib/cmake/boost_wserialization-1.75.0
├── c-ares -> ../../Cellar/c-ares/1.17.1/lib/cmake/c-ares
├── cereal
├── cppunit
├── cxx_simplelog
├── cxxopts
├── date
├── doctest -> ../../Cellar/doctest/2.4.5/lib/cmake/doctest
├── double-conversion -> ../../Cellar/double-conversion/3.1.5_1/lib/cmake/double-conversion
├── fmt -> ../../Cellar/fmt/7.1.3/lib/cmake/fmt
├── folly -> ../../Cellar/folly/2021.02.01.00/lib/cmake/folly
├── gflags -> ../../Cellar/gflags/2.2.2/lib/cmake/gflags
├── glog -> ../../Cellar/glog/0.4.0/lib/cmake/glog
├── grpc -> ../../Cellar/grpc/1.35.0/lib/cmake/grpc
├── gsl-lite
├── harfbuzz -> ../../Cellar/harfbuzz/2.7.4/lib/cmake/harfbuzz
├── range-v3 -> ../../Cellar/range-v3/0.11.0/lib/cmake/range-v3
├── re2 -> ../../Cellar/re2/20210201/lib/cmake/re2
├── scope
├── span
├── spdlog -> ../../Cellar/spdlog/1.8.2/lib/cmake/spdlog
├── tftpd
├── tomlplusplus
└── zlib

76 directories
Claus-iMac:example clausklein$ 
```

**Comment by TheLartians** [comment]
> Most project do not use version postfix

True, most projects ignore this, which is why we need package managers like brew and usually don't install or link to anything in the main lib directory. As you can see above, most of your libraries are actually just aliases to a prefixed directory, managed by brew. Using the prefixed include would native installation without running into the issues I mentioned, even without an external package manager such as brew.

For end-users of your library there would not be any difference anyways, as CMake automatically sets the correct includes accordingly.

**Comment by ClausKlein** [comment]
interesting is that the compiler doesn't see this:
```shell
Claus-iMac:example clausklein$ ninja -C build -t deps | egrep -i '(fmt|greeter)'
CMakeFiles/Greeter.dir/source/Greeter.cpp.o: #deps 236, deps mtime 1612777996507098442 (VALID)
    ../source/Greeter.cpp
    /usr/local/include/fmt/chrono.h
    /usr/local/include/fmt/format.h
    /usr/local/include/fmt/core.h
    /usr/local/include/fmt/format-inl.h
    /usr/local/include/fmt/locale.h
    ../include/greeter/greeter.h
Claus-iMac:example clausklein$ 
```

**Comment by TheLartians** [comment]
Yup, and this may break your installed projects if _fmt_ ever decides to change its API. The solution I know of is to either use install prefixes as _PackageProject_ recommends or install everything using a package manager such as _brew_ to set the correct prefixes before configuring.

**Comment by TheLartians** [comment]
That said, you're free to choose any `INCLUDE_DESTINATION` and `COMPATIBILITY` when using _PackageProject_, so only the CMake config and libraries are currently installed with a prefix by default. When multiple versions are, the [docs make me believe](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_SORT_ORDER.html) that CMake will automatically find the newest version using this config.
