### ISSUE TITLE
Possibility to create CPack installers

### ISSUE THREAD

**Issue by TheLartians** [TheLartians/PackageProject.cmake#2]
I have never worked with CPack before, but I think this could be useful.

**Comment by saxbophone** [comment]
I agree it could be useful. I've only dabbled with CPack previously, I found that for anything more complicated than a shell-archive or ZIP file, it was not very intuitive to use and debugging the output in a cross-platform way was compounded by the fact that many installer types are platform-specific.

That being said, actual usage of it from my memory is pretty simple (mainly just setting a bunch of variables and invoking CPack).

**Comment by TheLartians** [comment]
Initial support for CPack implemented in #35.
