### ISSUE TITLE
The PROJECT_VERSION_SUFFIX is always empty

### ISSUE THREAD

**Issue by ClausKlein** [TheLartians/PackageProject.cmake#21]
from [cmake_parse_arguments](https://cmake.org/cmake/help/latest/command/cmake_parse_arguments.html?highlight=cmake_parse_arguments) :
For the <options> keywords, these will always be defined, to TRUE or FALSE, whether the option is in the argument list or not.

see https://github.com/TheLartians/PackageProject.cmake/pull/20

**Comment by TheLartians** [comment]
Closed by #20
